---
- hosts: all
  connection: local
  become: no


  vars_prompt:
  - name: "vsphere_username"
    prompt: "Enter your vsphere username"
    private: yes
  - name: "vsphere_password"
    prompt: "Enter your vsphere password"
    private: yes

  tasks:
    - name: rebuild Windows ISO images to boot without key press
      when: inventory_hostname in groups["win2019"]
      include_tasks:
        file: "{{ playbook_dir }}/tasks//make_win_cd_bootable.yml"
        apply:
          become: true
      vars: 
        ansible_connection: local

