- hosts: all
  connection: local
  become: no


  vars_prompt:
  - name: "vsphere_username"
    prompt: "Enter your vsphere username"
    private: yes
  - name: "vsphere_password"
    prompt: "Enter your vsphere password"
    private: yes

  vars:
    esxi_hostname: "{{ hostvars[inventory_hostname]['esxi_host'] }}"
    esxi_ip: "{{ hostvars[inventory_hostname]['esxi_ip'] }}"
    vsphere_datacenter: ha-datacenter
    vsphere_datastore: "{{ hostvars[inventory_hostname]['datastore'] }}"
    vsphere_iso_datastore: QNAPDataStore
    vsphere_iso_directory: ISOs
    vsphere_hostname: vcsa.lab.clearfocustech.com
    vsphere_hostname: "{{ esxi_ip }}"
    vm_network: "{{ hostvars[inventory_hostname]['vm_network'] }}"
    iso_image: "{{ hostvars[inventory_hostname]['iso_image'] }}"
    ram_mb: "{{ hostvars[inventory_hostname]['ram_mb'] }}"
    cpu_count: "{{ hostvars[inventory_hostname]['cpu_count'] }}"
    disk_gb: "{{ hostvars[inventory_hostname]['disk_gb'] }}"
    unattend: "{{ hostvars[inventory_hostname]['unattend'] }}"
    iso_requires_keypress: False # Some Windows ISO install images require a key press to boot the install, if set to true, this will try and rebuild the ISO to skip that.
    folder_name: "/"

  tasks:
  - name: ensure we start from lock screen
    when: False
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      folder: "{{ folder_name }}"
      name: "{{ inventory_hostname }}"
      keys_send:
        - WINDOWS
      string_send: "l"
      validate_certs: False

  - name: CTRL ALT DEL to login
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
     hostname: "{{ vsphere_hostname }}"
     username: "{{ vsphere_username }}"
     password: "{{ vsphere_password }}"
     datacenter: "{{ vsphere_datacenter }}"
     folder: "{{ folder_name }}"
     name: "{{ inventory_hostname }}"
     moid: vm-42
     keys_send:
      - CTRL_ALT_DEL
     validate_certs: False

  - name: Send username
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
     hostname: "{{ vsphere_hostname }}"
     username: "{{ vsphere_username }}"
     password: "{{ vsphere_password }}"
     datacenter: "{{ vsphere_datacenter }}"
     folder: "{{ folder_name }}"
     name: "{{ inventory_hostname }}"
     string_send: "{{ hostvars[inventory_hostname]['local_admin_pass'] }}"
     validate_certs: False

  - name: Send enter
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
     hostname: "{{ vsphere_hostname }}"
     username: "{{ vsphere_username }}"
     password: "{{ vsphere_password }}"
     datacenter: "{{ vsphere_datacenter }}"
     folder: "{{ folder_name }}"
     name: "{{ inventory_hostname }}"
     keys_send:
       - ENTER
     validate_certs: False

  - name: Send news.google.com
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
     hostname: "{{ vsphere_hostname }}"
     username: "{{ vsphere_username }}"
     password: "{{ vsphere_password }}"
     datacenter: "{{ vsphere_datacenter }}"
     folder: "{{ folder_name }}"
     name: "{{ inventory_hostname }}"
     string_send: "news.google.com"
     validate_certs: False

  - name: Send enter
    delegate_to: localhost
    community.vmware.vmware_guest_sendkey:
     hostname: "{{ vsphere_hostname }}"
     username: "{{ vsphere_username }}"
     password: "{{ vsphere_password }}"
     datacenter: "{{ vsphere_datacenter }}"
     folder: "{{ folder_name }}"
     name: "{{ inventory_hostname }}"
     keys_send:
       - ENTER
     validate_certs: False
