- hosts: all
 
  vars:
    warning_banner: 'You are accessing a U.S. Gvovernment (USG) information System (IS)that is provided for USG-authorized use only.
By using this IS (which includes any attached device to this IS), you consent to the following conditions:
- The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduc(PM), law enforcement(LE), and counterintelligence (CI) investigations.
- At any time the USG may inspect and sieze data stored on this IS., 
- Communications using, or data stoered on, this IS are not private, subject to routine monitoring, interception, and search, and may be dislosed or used for any USG-authorized purpose. 
- This IS includes security measures (e.g., authentication and access controls) to protect USG interests --not for your personel benefit or privacy.'
    syslog_host: loghost.lab.local
    sshd_approved_macs: hmac-sha2-512,hmac-sha2-256,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
    sshd_approved_ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
    yum_repository: http://www.ctlab.com
    org_name: OT Lab
  tasks:
    - name: warning banner
      copy:
        content: "{{ warning_banner }}"
        dest: /etc/issue
                               
 
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
          - aide
                                 
    - name: SSH warning banner
      lineinfile:
        create: yes
        dest: /etc/ssh/sshd_config
        regexp: ^Banner
        line: Banner /etc/issue
        validate: sshd -t -f %s
       
    - name: Remote rsyslog host
      lineinfile:
        create: yes
        dest: /etc/rsyslog.d/loghost.conf
        regexp: '^\\*\\.\\*'
        line: "*.* @@{{ syslog_host }}"
        validate: rsyslogd -N 1 -f %s
    - name: Add linux admins to sudoers
      community.general.sudoers:
        name: linux-admins-all
        state: present
        group: linux admins
        commands: ALL

    - name: Setup AIDE
      when: False
      block: 

      - name: Check if AIDE is initialized
        stat:
          path: /var/lib/aide/aide.db.gz
        register: aide_db
     
      - name: Initialize AIDE
        when: aide_db.stat.exists == False
        command: /usr/sbin/aide --init
     
      - name: Move AIDE db
        when: aide_db.stat.exists == False
        command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
 
      - name: Configure AIDE
        cron:
          name: rune AIDE check
          minute: "05"
          hour: "04"
          weekday: "0"
          user: root
          job: "/usr/sbin/aide --check"
 
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
        enabled: yes
       
    - name: restart sshd
      service:
        name: sshd
        state: restarted       
        enabled: yes
       
    - name: Update all packages
      package:
        name: "*"
        state: latest
       
    - name: Configure Automatic updates
      when: False
      block:

      - name: remove Yum repositores
        shell: rm -f /etc/yum/repos/d/CentOS-*
                 
      - name: install local Yum repository
        command: curl {{ yum_repository }} -o /etc/yum.repos.d/{{ org_name}}.repo

      - name: Update yum-cron options
        lineinfile:
            dest: /etc/yum/yum-cron.conf
            regexp: "update_messages*=*"
            line: "update_messages = yes"
            create: yes
     
      - name: Update yum-cron options
        lineinfile:
            dest: /etc/yum/yum-cron.conf
            regexp: "download_updates*=*"
            line: "download_updates = yes"
            create: yes
     
      - name: Update yum-cron options
        lineinfile:
            dest: /etc/yum/yum-cron.conf
            regexp: "apply_updates*=*"
            line: "apply_updates = yes"
            create: yes 
 
       
