---
- hosts: all
  tasks:
  - name: Install bind and associated dependencies
    package:
      name: "{{ item }}"
      state: present
    become: yes
    with_items:
      - bind9
      - bind9utils

  - name: Enable bind on startup
    service:
      name: bind9
      state: started
      enabled: yes
    become: yes

  - name: Configure bind as required
    template:
      src: "templates/bind/{{ item }}"
      dest: "/etc/bind/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - named.conf.local
      - named.conf.options
    become: yes

  - name: Configure zones as required
    template:
      src: "{{ item.template_source }}"
      dest: "/etc/bind/db.{{ item.name }}"
      owner: root
      group: root
      mode: 0644
    with_items: "{{ zones }}"
    become: yes

  - name: Restart bind post-configure
    service:
      name: bind9
      state: restarted
    become: yes
