- hosts: all
  connection: local
  become: no


#  vars_prompt:
#  - name: "vsphere_username"
#    prompt: "Enter your vsphere username"
#    private: yes
#  - name: "vsphere_password"
#    prompt: "Enter your vsphere password"
#    private: yes
      
  vars:
    esxi_hostname: "{{ hostvars[inventory_hostname]['esxi_host'] }}"
    vsphere_datacenter: "{{ hostvars[inventory_hostname]['vsphere_datacenter'] }}"
    vsphere_datastore: "{{ hostvars[inventory_hostname]['vsphere_datastore'] }}"
    vsphere_iso_datastore: "{{ hostvars[inventory_hostname]['vsphere_iso_datastore'] }}"
    vsphere_iso_directory: "{{ hostvars[inventory_hostname]['vsphere_iso_folder'] }}"
    vsphere_hostname: "{{ hostvars[inventory_hostname]['vsphere_hostname'] }}"

    vsphere_username: "{{ lookup('env', 'VSPHERE_USERNAME') }}"
    vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"

  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware_guest_powerstate:
      validate_certs: False
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      name: "{{ inventory_hostname }}"
      state: powered-off

  - name: delete vm
    vmware_guest:
      validate_certs: False
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      name: "{{ inventory_hostname }}"
      state: absent
      delete_from_inventory: true

  - name: delete custom iso image from datastore
    vsphere_copy:
      validate_certs: False
      hostname: '{{ vsphere_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      path: "{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"
      state: absent
    delegate_to: localhost
