
- name: install first domain controller
  hosts: all

  tasks:
   - name: install AD Services
     win_feature:
       name: AD-Domain-Services
       include_management_tools: true
       include_sub_features: true
       state: present
     register: result

   - name: install domain
     win_domain: 
       dns_domain_name: "{{ domain_name }}"
       safe_mode_password: "{{ dsrm_pass }}'"
     register: ad

   - name: reboot server
     win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
     when: ad.changed

