- hosts: all
  connection: local
  become: no
 
  vars:
    esxi_hostname: "{{ hostvars[inventory_hostname]['esxi_host'] }}"
    vsphere_datacenter: "{{ hostvars[inventory_hostname]['vsphere_datacenter'] }}"
    vsphere_datastore: "{{ hostvars[inventory_hostname]['vsphere_datastore'] }}"
    vsphere_iso_datastore: "{{ hostvars[inventory_hostname]['vsphere_iso_datastore'] }}"
    vsphere_iso_directory: "{{ hostvars[inventory_hostname]['vsphere_iso_folder'] }}"
    vsphere_hostname: "{{ hostvars[inventory_hostname]['vsphere_hostname'] }}"

    vm_network: "{{ hostvars[inventory_hostname]['vm_network'] }}"
    iso_image: "{{ hostvars[inventory_hostname]['iso_image'] }}"
    ram_mb: "{{ hostvars[inventory_hostname]['ram_mb'] }}"
    cpu_count: "{{ hostvars[inventory_hostname]['cpu_count'] }}"
    disk_gb: "{{ hostvars[inventory_hostname]['disk_gb'] }}"
    local_user: "{{ hostvars[inventory_hostname]['local_admin'] }}"
    local_user_pass: "{{ hostvars[inventory_hostname]['local_admin_pass'] }}"
    root_pass: "{{ hostvars[inventory_hostname]['local_admin_pass'] }}"

 
    vsphere_username: "{{ lookup('env', 'VSPHERE_USERNAME') }}"
    vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
 
  tasks:
 
  - command: mktemp -d
    delegate_to: localhost
    register: tempdir
 
  - command: mktemp -d
    delegate_to: localhost
    register: loopdir
 
  - name: Check for the ISO on the local disk
    ansible.builtin.stat:
      path: "{{ playbook_dir }}/isos/{{ iso_image }}"
    register: local_iso

  - name: Print error if ISO does not exist locally
    when: not local_iso.stat.exists
    ansible.builtin.fail:
      msg: "Missing the ISO image, cannot proceed. Expected the file {{ playbook_dir }}/isos/{{ iso_image }}. Ensure the iso_image is set correctly int the inventory."

  - name: mount source iso image
    command: mount -o loop "{{ playbook_dir }}/isos/{{ iso_image }}" "{{ loopdir.stdout }}"
    delegate_to: localhost
 
  - name: copy source iso image contents to custom iso
    shell: cp -a -R "{{ loopdir.stdout }}"/. "{{ tempdir.stdout }}"
    delegate_to: localhost
 
  - name: create kickstart file on custom iso
    template:
      src: "{{ playbook_dir }}/templates/centos-kickstart.cfg.j2"
      dest: "{{ tempdir.stdout }}/ks.cfg"
 
  - name: Update boot options
    command: sed -i 's/append\ initrd\=initrd.img/append initrd=initrd.img\ ks\=cdrom:\/ks.cfg/' "{{ tempdir.stdout }}"/isolinux/isolinux.cfg
    delegate_to: localhost

  - name: create local build directory
    file: 
      path: "{{ playbook_dir }}/build"
      state: directory
 
  - name: create custom iso image
    #command: mkisofs -r -N -allow-leading-dots -d -J -T -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -V "{{ inventory_hostname_short }}" -boot-load-size 4 -boot-info-table -o build/{{ inventory_hostname }}.iso {{ tempdir.stdout }}
    command: genisoimage -o {{ playbook_dir }}/build/{{ inventory_hostname }}.iso -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -J -R -v -T -V 'CentOS 7 x86_64' {{ tempdir.stdout }}
    delegate_to: localhost

  - name: add checksum to custom iso image
    command: implantisomd5 {{ playbook_dir }}/build/{{ inventory_hostname }}.iso
    delegate_to: localhost
 
  - name: unmount source iso image
    command: umount "{{ loopdir.stdout }}"
    delegate_to: localhost

  - name: Create a VM folder on given datacenter
    when: False
    vcenter_folder:
      hostname: '{{ vsphere_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      datacenter_name: "{{ vsphere_datacenter }}"
      folder_name: "{{ vsphere_iso_directory }}"
      folder_type: vm
      state: present
      validate_certs: False
    register: vm_folder_creation_result
    delegate_to: localhost
 
  - name: upload custom ISO for Kickstart
    vsphere_copy:
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_iso_datastore }}"
      src: "{{ playbook_dir }}/build/{{ inventory_hostname }}.iso"
      path: "{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"
      timeout: 120
      validate_certs: False
 
  - name: cleanup temp directories
    file:
      path: "{{ loopdir.stdout }}"
      state: absent
 
  - name: cleanup temp directories
    file:
      path: "{{ tempdir.stdout }}"
      state: absent
 
  - name: cleanup custom iso
    file:
      path: "{{ playbook_dir }}/build/{{ inventory_hostname }}.iso"
      state: absent
 
  - name: create vm
    vmware_guest:
      validate_certs: False
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      esxi_hostname: "{{ esxi_hostname }}"
      folder: /
      name: "{{ inventory_hostname }}"
      guest_id: ubuntu64Guest
      state: poweredon
      disk:
        - size_gb: 32
          type: thin
          datastore: "{{ vsphere_datastore }}"
      networks:
        - name: "{{ vm_network }}"
      hardware:
        memory_mb: "{{ ram_mb }}"
        num_cpus: "{{ cpu_count }}"
      cdrom:
        type: iso
        iso_path: "[{{ vsphere_iso_datastore }}] /{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"


  - name: delete custom iso image from datastore
    when: False
    vsphere_copy:
      validate_certs: False
      hostname: '{{ vsphere_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      path: "{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"
      state: absent
    delegate_to: localhost
